### ISSUE TITLE
Establish quality standards - the 2nd level

### ISSUE THREAD

**Issue by carstingaxion** [figuren-theater/code-quality#54]
```[tasklist]
### Tasks
- [ ] Create new issue template
- [ ] Add cognitive complexity CS checks
- [ ] Update WPCS to ^3.0
- [ ] Add minimal phpunit testing infrastructure (altis uses codeception, alternative wp_mock by 10up)
- [ ] Add acceptance testing infrastructure (altis uses codeception, alternative wp_acceptance by 10up)
```
