### ISSUE TITLE
Allow more flexible handling of files where to bump the version 

### ISSUE THREAD

**Issue by carstingaxion** [figuren-theater/code-quality#59]
Currently the used GitHub action looks for the existence of a plugin.phpˋ and if any, it’ll update the typical WordPress formatted version string in the doc-block.

```[tasklist]
### Tasks
- [ ] This action should allow the file to be given via an attribute.
- [ ] The action knows common replacement patterns for typical other files:
- [ ] ˋpackage.jsonˋ
- [ ] ˋlanguages/TEXTDOMAIN.potˋ
- [ ] ˋREADME.mdˋ (which replaces a readme.txt for .org)
- [ ] A *foreign* replacement pattern can also be provided as an attribute
- [ ] 
```

**Comment by carstingaxion** [comment]
https://github.com/sc0ttkclark/wporg-replace-helper

**Comment by carstingaxion** [comment]
Better https://github.com/sc0ttkclark/wporg-replace

**Comment by carstingaxion** [comment]
https://github.com/marketplace/actions/wordpress-org-text-replace
